from abc import ABC, abstractmethod
from typing import List

class LLMClient(ABC):
    @abstractmethod
    def answer(self, question: str, context_chunks: List[str]) -> str:
        """
        Generate an answer to a question based on provided context chunks.
        
        Args:
            question: The user's question to answer
            context_chunks: List of text chunks containing context for answering the question
            
        Returns:
            str: The answer generated by the language model
        """
        pass 